version: "2"
services:
  forntend:
    build: ./frontend
    ports:
       - '3000:3000'
    depends_on:
      - web
  web:
    build: ./server
    ports:
      - "80:80"
  db:
    image: "mysql:5.7.37-oracle"
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=000000
      - MYSQL_DATABASE=patika
